### PR TITLE
Add DHCLIENT DNS config for RedHat 8

### PR DESCRIPTION
**Pull request by gartemiev**

### CODE REVIEW

**Comment by mattock** [comment]
I would add a conditional to check for Red Hat 8 to init.pp, refactoring the conditionals there as needed. Then have a separate networkmanager.pp for all those current and future operating systems that use Network Manager for resolver configuration.

**Comment by gartemiev** [comment]
> I would add a conditional to check for Red Hat 8 to init.pp, refactoring the conditionals there as needed. Then have a separate networkmanager.pp for all those current and future operating systems that use Network Manager for resolver configuration.

I assume you want to call networkmanager.pp in condition for Redhat 8 in init.pp after calling dhclient.pp?

**Comment by mattock** [comment]
The original design in the module is to split into separate files by resolver backend. That why I was suggesting separate networkmanager.pp. I did not know that Networkmanager can use different resolver backends (checked the [docs](https://developer.gnome.org/NetworkManager/stable/NetworkManager.conf.html)).

So basically you're making NetworkManager stop trying to manage DNS itself, and instead rely in dhclient and the override file ("supersede domain-name-servers ${servers_string};") to do manage resolver entries?

I will do some checks and see if this has a chance of working outside of EC2.

**Comment by gartemiev** [comment]
> The original design in the module is to split into separate files by resolver backend. That why I was suggesting separate networkmanager.pp. I did not know that Networkmanager can use different resolver backends (checked the [docs](https://developer.gnome.org/NetworkManager/stable/NetworkManager.conf.html)).
> 
> So basically you're making NetworkManager stop trying to manage DNS itself, and instead rely in dhclient and the override file ("supersede domain-name-servers ${servers_string};") to do manage resolver entries?
> 
> I will do some checks and see if this has a chance of working outside of EC2.

Both on RHEL7 and RHEL8, NetworkManager supports two DHCP plugins: "dhclient" and "internal".

On RHEL7, the default is "dhclient".
On RHEL8, the default changed to "internal

The internal client does not use dhclient, and does not honor /etc/dhcp.

There is nothing wrong with the internal client (it's just not as configurable as dhclient, which is a problem if you require that configuration).
There is also nothing particularly wrong with the dhclient plugin. What I do is add that configuration from erb template and then doing restart of network manager in order that configuration file take effect. I do not stop anything there.

I would prefer to leave at as it is now since it blocks other task which I have and later we can come back to this regarding refactoring/optimization.

**Comment by mattock** [comment]
I ran into the problem you're solving some months ago in another environment, so I know the pain. Back then I decided to work around the issue in a profile and here I am back at the same problem. What goes around comes around :smile:.

I'm more cautious with public Puppet module because other people may be using them and I don't want to break things for other people. Fortunately this module is not (yet) in Puppet Forge so I don't think many people are using it. Also, different clouds have different base images, so what works in Amazon EC2 is not guaranteed to work elsewhere, unfortunately.

NetworkManager and systemd-resolved have complicated resolver configuration for the simple use-case. Some time in the near future I need to fix puppet-resolver "for good" to work well-enough with both of them. Otherwise this problem will just keep cropping up again and again.

That said, I can live with this for now.

**Pull request merged**
